name: Main workflow

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - 4.14.x
        include:
          - os: windows-latest
            ocaml-compiler: ocaml-variants.4.14.0+msvc64c

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ contains(matrix.ocaml-compiler, 'msvc64') }}

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Remove conflicting /usr/bin/link
        run: rm D:\cygwin\bin\link.exe
        if: ${{ contains(matrix.ocaml-compiler, 'msvc64') }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
